global:
  scrape_interval: 30s

scrape_configs:
  - job_name: 'weather-app'
    static_configs:
      - targets: ['host.docker.internal:8000']  # Endpoint externo

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']
