{
 "title": "weather",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Hardware Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "% Uso de CPU X Core",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cpu_per_core_usage_percentage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memoria Libre",
   "type": "stat",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "memory_free_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memoria Libre",
   "type": "stat",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "memory_usage_percentage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "% de uso de Disco",
   "type": "stat",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "disk_usage_percentage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "% de uso de Disco",
   "type": "stat",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "disk_free_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Api Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP_STATUS /weather/average/day",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "weather_api_request_count_total{endpoint=\"/weather/average/day\", http_status=\"200\"}",
       "legendFormat": "OK"
      },
      {
       "expr": "weather_api_request_count_failed_total{endpoint=\"/weather/average/day\", http_status=\"500\"}",
       "legendFormat": "Error"
      }
     ]
    },
    {
     "title": "HTTP_STATUS /weather/current",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "weather_api_request_count_total{endpoint=\"/weather/current\", http_status=\"200\"}",
       "legendFormat": "OK"
      },
      {
       "expr": "weather_api_request_count_failed_total{endpoint=\"/weather/current\", http_status=\"500\"}",
       "legendFormat": "Error"
      }
     ]
    },
    {
     "title": "HTTP_STATUS /weather/average/week",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "weather_api_request_count_total{endpoint=\"/weather/average/week\", http_status=\"200\"}",
       "legendFormat": "OK"
      },
      {
       "expr": "weather_api_request_count_failed_total{endpoint=\"/weather/average/week\", http_status=\"500\"}",
       "legendFormat": "Error"
      }
     ]
    },
    {
     "title": "HTTP_STATUS /weather/average/week",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 34 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "weather_api_request_count_total{endpoint=\"/weather/average/week\"}",
       "legendFormat": "OK"
      },
      {
       "expr": "weather_api_request_count_failed_total{endpoint=\"/weather/average/week\", http_status=\"500\"}",
       "legendFormat": "Error"
      }
     ]
    }
   ]
  }
 ]
}