{
 "title": "El Tiempo Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Business Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperatura Actual",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "weather_current_temperature", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "% de Humedad",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "weather_current_humidity", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Presión Atmosférica",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "weather_current_pressure", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Temperatura Promedio Semanal",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weather_average_temperature_week",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperatura promedio del dia",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weather_average_temperature_day",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Hardware Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "% Uso de CPU X Core",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cpu_per_core_usage_percentage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memoria Libre",
   "type": "stat",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "memory_free_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "% de Uso de Memoria",
   "type": "stat",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "memory_usage_percentage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "% de uso de Disco",
   "type": "stat",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "disk_usage_percentage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "% de uso de Disco",
   "type": "stat",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "disk_free_bytes", "legendFormat": "__auto" }
   ]
  },
  { "title": "Api Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "HTTP_STATUS /weather/average/day",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weather_api_request_count_total{endpoint=\"/weather/average/day\", http_status=\"200\"}",
     "legendFormat": "OK"
    },
    {
     "expr": "weather_api_request_count_failed_total{endpoint=\"/weather/average/day\", http_status=\"500\"}",
     "legendFormat": "Error"
    }
   ]
  },
  {
   "title": "HTTP_STATUS /weather/current",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weather_api_request_count_total{endpoint=\"/weather/current\", http_status=\"200\"}",
     "legendFormat": "OK"
    },
    {
     "expr": "weather_api_request_count_failed_total{endpoint=\"/weather/current\", http_status=\"500\"}",
     "legendFormat": "Error"
    }
   ]
  },
  {
   "title": "HTTP_STATUS /weather/average/week",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weather_api_request_count_total{endpoint=\"/weather/average/week\", http_status=\"200\"}",
     "legendFormat": "OK"
    },
    {
     "expr": "weather_api_request_count_failed_total{endpoint=\"/weather/average/week\", http_status=\"500\"}",
     "legendFormat": "Error"
    }
   ]
  },
  {
   "title": "Latencia  /weather/average/day",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weather_api_request_latency_seconds_count{endpoint=\"/weather/average/day\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "weather_api_request_latency_seconds_sum{endpoint=\"/weather/average/day\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latencia  /weather/current",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weather_api_request_latency_seconds_count{endpoint=\"/weather/current\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "weather_api_request_latency_seconds_sum{endpoint=\"/weather/current\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latencia  /weather/average/week",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 68 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weather_api_request_latency_seconds_count{endpoint=\"/weather/average/week\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "weather_api_request_latency_seconds_sum{endpoint=\"/weather/average/week\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}